
package com.jws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JwsService", targetNamespace = "http://jws.com/", wsdlLocation = "http://172.16.100.51/Jws?wsdl")
public class JwsService
    extends Service
{

    private final static URL JWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JWSSERVICE_EXCEPTION;
    private final static QName JWSSERVICE_QNAME = new QName("http://jws.com/", "JwsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.100.51/Jws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JWSSERVICE_WSDL_LOCATION = url;
        JWSSERVICE_EXCEPTION = e;
    }

    public JwsService() {
        super(__getWsdlLocation(), JWSSERVICE_QNAME);
    }

    public JwsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JWSSERVICE_QNAME, features);
    }

    public JwsService(URL wsdlLocation) {
        super(wsdlLocation, JWSSERVICE_QNAME);
    }

    public JwsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JWSSERVICE_QNAME, features);
    }

    public JwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JwsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Jws
     */
    @WebEndpoint(name = "JwsPort")
    public Jws getJwsPort() {
        return super.getPort(new QName("http://jws.com/", "JwsPort"), Jws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Jws
     */
    @WebEndpoint(name = "JwsPort")
    public Jws getJwsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jws.com/", "JwsPort"), Jws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JWSSERVICE_EXCEPTION!= null) {
            throw JWSSERVICE_EXCEPTION;
        }
        return JWSSERVICE_WSDL_LOCATION;
    }

}
