
package com.jws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Jws", targetNamespace = "http://jws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Jws {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getData", targetNamespace = "http://jws.com/", className = "com.jws.GetData")
    @ResponseWrapper(localName = "getDataResponse", targetNamespace = "http://jws.com/", className = "com.jws.GetDataResponse")
    @Action(input = "http://jws.com/Jws/getDataRequest", output = "http://jws.com/Jws/getDataResponse")
    public String getData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "manualExtractData", targetNamespace = "http://jws.com/", className = "com.jws.ManualExtractData")
    @ResponseWrapper(localName = "manualExtractDataResponse", targetNamespace = "http://jws.com/", className = "com.jws.ManualExtractDataResponse")
    @Action(input = "http://jws.com/Jws/manualExtractDataRequest", output = "http://jws.com/Jws/manualExtractDataResponse")
    public boolean manualExtractData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
